version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
        environment:
            DB_CONNECTION: mysql
            DB_HOST: actuacioncompleta.com
            DB_PORT: 3306
            DB_DATABASE: actuac6_memory_game
            DB_USERNAME: actuac6_guest
            DB_PASSWORD: Guest2024!

    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: actuac6_memory_game
            MYSQL_USER: actuac6_guest
            MYSQL_PASSWORD: Guest2024!
            MYSQL_ROOT_PASSWORD: root
